---
title: "Estatus subjetivo y Percepción de Mérito"
output:
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warnings = FALSE,
  message = FALSE
)
```

```{r paquetes}
library(elsoc)
library(survey)
library(tidyverse)
library(ggalluvial)
library(scales)
library(sjlabelled)
library(sjmisc)
```

```{r cargar-bases}
remove(list = ls())
# Cargar bases desde Dataverse
load(url("https://dataverse.harvard.edu/api/access/datafile/10797987")) # long 2016-2023
load(url("https://dataverse.harvard.edu/api/access/datafile/10797986")) # wide 2016-2023

frq(elsoc_wide_2016_2023$m28_w05)
```

```{r recodificar-vars}
elsoc_long_2016_2023[elsoc_long_2016_2023 == -888 | elsoc_long_2016_2023 == -999 | elsoc_long_2016_2023 == 994 | elsoc_long_2016_2023 == 995 | elsoc_long_2016_2023 == 996 | elsoc_long_2016_2023 == -666 | elsoc_long_2016_2023 == -777] <- NA # varias categorías a NA

# Recodificar variables necesarias una sola vez
library(dplyr)
library(car)
library(sjlabelled)

elsoc_base <- elsoc_long_2016_2023 %>%
  filter(tipo_atricion == 1, muestra == 1) %>%
  mutate(
    # Estatus subjetivo: propio, padres, hijos
    ess_propio = factor(car::recode(d01_01, "c(0,1,2,3,4)=1; c(5)=2; c(6,7,8,9,10)=3; else=NA"),
                        levels = c(1, 2, 3),
                        labels = c("Bajo (0 a 4)", "Medio (5)", "Alto (6 a 10)")),
    ess_fam = factor(car::recode(d01_02, "c(0,1,2,3,4)=1; c(5)=2; c(6,7,8,9,10)=3; else=NA"),
                     levels = c(1, 2, 3),
                     labels = c("Bajo (0 a 4)", "Medio (5)", "Alto (6 a 10)")),
    ess_hijo = factor(car::recode(d01_03, "c(0,1,2,3,4)=1; c(5)=2; c(6,7,8,9,10)=3; else=NA"),
                      levels = c(1, 2, 3),
                      labels = c("Bajo (0 a 4)", "Medio (5)", "Alto (6 a 10)")),

    # Movilidad subjetiva intergeneracional e intrageneracional
    pmov_ess = d01_03 - d01_01,
    pmov_ess_fc = factor(car::recode(d01_03 - d01_01, "-10:-1=1; 0=2; 1:2=3; 3:10=4; else=NA"),
                         levels = c(1,2,3,4),
                         labels = c("Descendente (-10 a -1)", "Inmovilidad (0)", 
                                    "Limitada (1 a 2)", "Ascendente (3 a 10)")),
    tmov_ess = d01_01 - d01_02,
    tmov_ess_fc = factor(car::recode(d01_01 - d01_02, "-10:-1=1; 0=2; 1:2=3; 3:10=4; else=NA"),
                         levels = c(1,2,3,4),
                         labels = c("Descendente (-10 a -1)", "Inmovilidad (0)", 
                                    "Limitada (1 a 2)", "Ascendente (3 a 10)")),
    
    satisf_dem = factor(car::recode(c01, "1:2 = 1;  3 = 2;  4:5 = 3;  else = NA"),
                        levels = c(1,2,3),
                        labels = c("Baja", "Media", "Alta")),
    
    # Percepción de justicia distributiva

    just_esfu_fc =  factor(car::recode(c18_09, "1:2 = 1;  3 = 2;  4:5 = 3;  else = NA"),
                           levels = c(1,2,3),
                           labels = c("Baja", "Media", "Alta")),
    
    just_inte_fc =  factor(car::recode(c18_10, "1:2 = 1;  3 = 2;  4:5 = 3;  else = NA"),
                           levels = c(1,2,3),
                           labels = c("Baja", "Media", "Alta")),
    
    # Confianza instituciones
    cond_inst = rowMeans(select(., c05_01, c05_02, c05_07), na.rm = TRUE)
    
  ) %>%
  sjlabelled::as_label(ola)


N_muestra <- elsoc_base %>%
  summarise(N = n() / n_distinct(ola)) %>%
  pull(N)  

caption_elsoc <- paste0("Fuente: ELSOC 2016-2023. Muestra ponderada y sin atrición entre olas (N = ", N_muestra, ")")

frq(elsoc_base$satisf_dem)
```

# Estatus

## Estatus subjetivo
```{r ess}
datos_ess <- elsoc_base %>% 
  filter(!is.na(ess_propio)) %>%
  prop(x = ess_propio, by = ola)

g_ess <- datos_ess %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(ess_propio), 
             label = scales::percent(prop, accuracy = .1))) + 
  geom_col(position = 'stack') +
  geom_text(position = position_stack(vjust = .5),
            size = 2.75, color = 'black') +
  scale_y_continuous(labels = percent) + 
  scale_fill_viridis_d(option = 'viridis', begin = .1, end = .9) +
  theme_bw() +
  theme(legend.position = 'top', legend.title = element_blank()) +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep(c('black', 'black', 'white'), 7)) +
  labs(title = "Estatus social subjetivo",
       subtitle = "En una escala donde 0 es lo mas bajo y 10 lo más alto, ¿Dónde se ubicaría usted en\nla sociedad chilena?",
       y = NULL, x = NULL,
       caption = caption_elsoc)

ggsave(g_ess, filename = "../3_output/g_ess.png", width = 8, height = 5, dpi = 300, units = "in")

g_ess
```

## Promedio estatus
```{r ess-total}
datos_ess_total <- elsoc_base %>%
  filter(!is.na(d01_01), !is.na(d01_02), !is.na(d01_03)) %>%
  group_by(ola) %>%
  summarise(
    essp_prom = weighted.mean(d01_02, ponderador02, na.rm = TRUE),
    essh_prom = weighted.mean(d01_03, ponderador02, na.rm = TRUE),
    ess_prom  = weighted.mean(d01_01, ponderador02, na.rm = TRUE),
  ) %>%
  mutate(
    `Estatus social\npadres` = essp_prom,
    `Estatus social\nhijos`  = essh_prom,
    `Estatus social\nactual` = ess_prom
  ) %>%
  dplyr::select(-starts_with("ess")) %>%
  pivot_longer(-ola, names_to = "Dimensión", values_to = "Promedio") %>%
  mutate(
    Promedio = round(Promedio, 2),
    Dimensión = factor(Dimensión, levels = c(
      "Estatus social\nhijos",
      "Estatus social\nactual",
      "Estatus social\npadres"
    ))
  )

g_ess_total <- datos_ess_total %>%
  ggplot(aes(x = ola, y = Promedio, group = Dimensión, color = Dimensión, label = Promedio)) +
  geom_line(size = 1) +
  geom_point(size = 2) +
  geom_text(vjust = -0.8, size = 3.5, show.legend = F) +  
  scale_y_continuous(limits = c(0, 10)) +
  scale_color_viridis_d(begin = .1, end = .8, direction = 1, option = "viridis") +
  theme_bw() +
  theme(
    legend.position = "top",
    legend.title = element_blank()
  ) +
  labs(
    title = "Estatus social subjetivo promedio",
    x = NULL,
    y = NULL,
    caption = caption_elsoc,
  )

ggsave(g_ess_total, filename = "../3_output/g_ess_total.png", width = 8, height = 5, dpi = 300, units = "in")

g_ess_total
```


## Trayectorias de movilidad
```{r tmov-ess}
datos_tmov_ess <- elsoc_base %>% 
  filter(!is.na(tmov_ess_fc)) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = tmov_ess_fc, by = ola, na.rm = T)

g_tmov_ess <- 
  datos_tmov_ess %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(tmov_ess_fc), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(begin = .11, end = .99, direction = 1, option = 'viridis') +
  scale_y_continuous(labels = scales::percent) + 
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep(c('black', 'black', 'white', 'white'), 7)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  labs(title = "Trayectoria de movilidad social subjetiva",
       subtitle = "Diferencia entre el estatus actual del encuestado y el estatus de sus padres",
       y = NULL, x = NULL,
       caption = caption_elsoc)
g_tmov_ess

ggsave(g_tmov_ess, filename = "../3_output/g_tmov_ess.png", width = 8, height = 5, dpi = 300, units = "in")
```

```{r pmov-ess}
datos_pmov_ess <- elsoc_base %>% 
  filter(!is.na(pmov_ess_fc)) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = pmov_ess_fc, by = ola, na.rm = T)

g_pmov_ess <- 
  datos_pmov_ess %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(pmov_ess_fc), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(begin = .11, end = .99, direction = 1, option = 'viridis') +
  scale_y_continuous(labels = scales::percent) + 
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep(c('black', 'black', 'white', 'white'), 7)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  labs(title = "Perspectiva de movilidad social subjetiva",
       subtitle = "Diferencia entre el estatus esperado de los hijos y el estatus actual del encuestado",
       y = NULL, x = NULL,
       caption = caption_elsoc)

ggsave(g_pmov_ess, filename = "../3_output/g_pmov_ess.png", width = 8, height = 5, dpi = 300, units = "in")

g_pmov_ess
```



## Estatus de origen versus actual
```{r ess-vs}
datos_ess_vs <- elsoc_base %>% 
  filter(!is.na(ess_fam), !is.na(ess_propio), ola == "2023") %>% 
  prop(x = ess_propio, by = ess_fam, na.rm = TRUE)

g_ess_vs <- datos_ess_vs %>% 
  ggplot(aes(x = ess_fam, y = prop, fill = fct_rev(ess_propio),
             label = percent(prop, accuracy = .1))) +
  geom_col(position = "stack") +
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep(c('black', 'black', 'white'), 3)) + 
  scale_fill_viridis_d(option = "viridis", begin = .1, end = .9) +
  scale_y_continuous(labels = percent) +
  theme_bw() +
  theme(legend.position = "top", legend.title = element_blank()) +
  labs(
    title = "Estatus actual del encuestado según estatus de origen (2023)",
    x = "Estatus social subjetivo de padres",
    y = NULL,
    caption = caption_elsoc
  )

ggsave(g_ess_vs, filename = "../3_output/g_ess_vs.png", width = 8, height = 5, dpi = 300, units = "in")

g_ess_vs
```

# Justicia distributiva

```{r}
datos_just_dist <- elsoc_long_2016_2023 %>% 
  filter(tipo_atricion == 1 & muestra == 1) %>%  
  select(c18_09, c18_10, ola, ponderador02, segmento_disenno, estrato_disenno) %>% 
  pivot_longer(cols = c(c18_09, c18_10)) %>% 
  filter(!value %in% c(-888, -999)) %>% 
  prop(value %in% c(4,5), by = c(ola, name), na.rm = TRUE) %>% 
  mutate(name = factor(name,
                       levels = c('c18_09', 'c18_10'),
                       labels = c('Personas son recompensadas\npor su esfuerzo',
                                  'Personas son recompensadas\npor su inteligencia')),
         ola_lab = as_label(ola))  # agrega versión con etiqueta

g_just_dist <- datos_just_dist %>% 
  ggplot(aes(y = prop, x = ola, color = fct_rev(name), group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  scale_x_continuous(breaks = datos_just_dist$ola, labels = datos_just_dist$ola_lab) +
  scale_color_viridis_d(begin = 0, end = .66, direction = 1, option = 'viridis') +
  geom_text(vjust = -0.8, size = 2.75, show.legend = FALSE) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  labs(title = "Creencia en valores meritocráticos",
        subtitle = "Porcentaje que responde de acuerdo o muy de acuerdo",
        x = NULL,
        y = NULL,
        caption = caption_elsoc)

ggsave(g_just_dist, filename = "../3_output/g_just_dist.png", width = 8, height = 5, dpi = 300, units = "in")

g_just_dist

```
# Confianza en instituciones

```{r}
datos_conf_inst <- elsoc_long_2016_2023 %>%
  filter(tipo_atricion == 1 & muestra == 1) %>%
  select(c05_01, c05_02, c05_07, ola, ponderador02, segmento_disenno, estrato_disenno) %>%
  pivot_longer(cols = c(c05_01, c05_02, c05_07)) %>%
  filter(!value %in% c(-888, -999)) %>%
  prop(value %in% c(4,5), by = c(ola, name), na.rm = TRUE) %>%
  mutate(name = factor(name,
                       levels = c("c05_01", "c05_02", "c05_07"),
                       labels = c("Confianza en\nel Gobierno",
                                  "Confianza en\nlos Partidos Políticos",
                                  "Confianza en\nel Congreso Nacional")),
         
         ola_lab = as_label(ola))  # agrega versión con etiqueta

g_conf_inst <- datos_conf_inst %>% 
  ggplot(aes(y = prop, x = ola, color = fct_rev(name), group = name,
             label = scales::percent(prop, accuracy = .1))) +
  theme_bw() +   
  geom_line(size = 1) +
  geom_point(size = 1.8) +
  scale_y_continuous(labels = scales::percent,
                     limits = c(0,1)) +
  scale_x_continuous(breaks = datos_just_dist$ola, labels = datos_just_dist$ola_lab) +
  ylab(NULL) +
  xlab(NULL) +
  scale_color_viridis_d(begin = 0, end = .66, direction = 1, option = 'viridis') +
  geom_text(vjust = -0.8, size = 2.75, show.legend = FALSE) +
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  labs(title = "Confianza en instituciones",
        subtitle = "Porcentaje que responde bastante o mucha confianza",
        x = NULL,
        y = NULL,
        caption = caption_elsoc)

ggsave(g_just_dist, filename = "../3_output/g_just_dist.png", width = 8, height = 5, dpi = 300, units = "in")

g_conf_inst
```
```{r tmov-ess}
datos_satisf_demo <- elsoc_base %>% 
  filter(!is.na(satisf_dem)) %>%
  sjlabelled::as_label(ola) %>% 
  prop(x = satisf_dem, by = ola, na.rm = T)

g_satisf_demo <- 
  datos_satisf_demo %>% 
  ggplot(aes(y = prop, x = ola, fill = fct_rev(satisf_dem), 
             label = as.character(scales::percent(prop, accuracy = .1)))) + 
  theme_bw() + 
  geom_col(position = 'Stack') +
  scale_fill_viridis_d(begin = .11, end = .99, direction = 1, option = 'viridis') +
  scale_y_continuous(labels = scales::percent) + 
  geom_text(position = position_stack(vjust = .5),
            size= 2.75, color = rep(c('black', 'black', 'white'), 7)) + 
  theme(legend.position = 'top',
        legend.title = element_blank()) +
  labs(title = "Satisfacción con la democracia",
       subtitle = "Alta (Bastante o muy satisfecho) | Media = (Algo insatisfecho) | Baja = (Nada o poco insatisfecho)",
       y = NULL, x = NULL,
       caption = caption_elsoc)
g_satisf_demo

ggsave(g_satisf_demo, filename = "../3_output/g_satisf_demo.png", width = 8, height = 5, dpi = 300, units = "in")
```

# Movilidad y cohesión

```{r}
datos_satis_ess <- elsoc_base %>% 
  filter(!is.na(tmov_ess_fc), !is.na(satisf_dem)) %>% 
  prop(x = satisf_dem, by = c(tmov_ess_fc, ola), na.rm = TRUE) %>% 
  filter(satisf_dem == "Baja",
         ola %in% c("2016", "2021", "2023")) 

g_satis_ess <- datos_satis_ess %>% 
  ggplot(aes(x = tmov_ess_fc, y = prop, fill = ola,
             label = percent(prop, accuracy = .1))) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5, size = 2.75) +
  scale_fill_viridis_d(option = "viridis", begin = .1, end = .9) +
  scale_y_continuous(labels = percent, limits = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "top", legend.title = element_blank()) +
  labs(
    title = "Insatisfacción con la democracia según trayectoria de movilidad",
    subtitle = "Porcentaje que responde nada o poco satisfecho",
    x = "Trayectoria de movilidad social subjetiva",
    y = NULL,
    caption = caption_elsoc
  )

g_satis_ess

ggsave(g_satis_ess, filename = "../3_output/g_satis_ess.png", width = 8, height = 5, dpi = 300, units = "in")
```
```{r}
datos_esfu <- elsoc_base %>% 
  filter(!is.na(tmov_ess_fc), !is.na(just_esfu_fc)) %>% 
  prop(x = just_esfu_fc, by = c(tmov_ess_fc, ola), na.rm = TRUE) %>% 
  filter(just_esfu_fc == "Alta",
         ola %in% c("2016", "2021", "2023")) 

g_esfu <- datos_esfu %>% 
  ggplot(aes(x = tmov_ess_fc, y = prop, fill = ola,
             label = percent(prop, accuracy = .1))) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5, size = 2.75) +
  scale_fill_viridis_d(option = "viridis", begin = .1, end = .9) +
  scale_y_continuous(labels = percent, limits = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "top", legend.title = element_blank()) +
  labs(
    title = "Creencia en que las personas son recompensadas por su esfuerzo",
    subtitle = "Porcentaje que responde de acuerdo o muy de acuerdo",
    x = "Trayectoria de movilidad social subjetiva",
    y = NULL,
    caption = caption_elsoc
  )

g_esfu

ggsave(g_esfu, filename = "../3_output/g_esfu.png", width = 8, height = 5, dpi = 300, units = "in")

```

```{r}
datos_inte <- elsoc_base %>% 
  filter(!is.na(tmov_ess_fc), !is.na(just_inte_fc)) %>% 
  prop(x = just_inte_fc, by = c(tmov_ess_fc, ola), na.rm = TRUE) %>% 
  filter(just_inte_fc == "Alta",
         ola %in% c("2016", "2021", "2023")) 

g_inte <- datos_inte %>% 
  ggplot(aes(x = tmov_ess_fc, y = prop, fill = ola,
             label = percent(prop, accuracy = .1))) +
  geom_col(position = position_dodge(width = 0.9)) +
  geom_text(position = position_dodge(width = 0.9), vjust = -0.5, size = 2.75) +
  scale_fill_viridis_d(option = "viridis", begin = .1, end = .9) +
  scale_y_continuous(labels = percent, limits = c(0, 1)) +
  theme_bw() +
  theme(legend.position = "top", legend.title = element_blank()) +
  labs(
    title = "Creencia en que las personas son recompensadas por su inteligencia",
    subtitle = "Porcentaje que responde de acuerdo o muy de acuerdo",
    x = "Trayectoria de movilidad social subjetiva",
    y = NULL,
    caption = caption_elsoc
  )

g_inte

ggsave(g_inte, filename = "../3_output/g_inte.png", width = 8, height = 5, dpi = 300, units = "in")

```

