---
title: "Variables movilidad y cohesión"
output: pdf_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Estatus social subjetivo

**Variable:** `d01_01`  
**Etiqueta:** *Estatus Social Subjetivo: Donde se ubicaría ud. en la sociedad chilena*  
- **Fraseo:** *En nuestra sociedad, hay grupos que tienden a ubicarse en los niveles más altos y grupos que tienden a ubicarse en los niveles más bajos de la sociedad. Usando la escala presentada, donde 0 es el nivel más bajo y 10 el nivel más alto,  ¿Dónde se ubicaría usted en la sociedad chilena?*

**Variable:** `d01_02`  
**Etiqueta:** *Estatus Social Subjetivo: Donde se ubicaría la familia en la que usted creció*  
- **Fraseo:** *Y pensando en la familia en la que usted creció, ¿dónde se ubicarían ellos en esta escala?*

**Variable:** `d01_03`  
**Etiqueta:** *Estatus Social Subjetivo: Donde se ubicarían sus hijos*  
- **Fraseo:** *Si usted tiene actualmente hijos o si los tuviera en el futuro, ¿dónde cree usted que se ubicarían ellos?*

# Nivel educacional

**Variable:** `m01`  
**Etiqueta:** *Nivel educacional*  
- **Fraseo:** *¿Cuál es su nivel educacional? Indique el tipo de estudio actual (si estudia actualmente) o el último tipo aprobado (si no estudia actualmente).*

**Variable:** `m27`  
**Etiqueta:** *Nivel educacional del padre*  
- **Fraseo:** *¿Cuál es/fue el nivel educacional de su padre?*

**Variable:** `m28`  
**Etiqueta:** *Nivel educacional de la madre*  
- **Fraseo:** *¿Cuál es/fue el nivel educacional de su madre?*

# Percepción de élites

**Variable:** `d24_01`  
**Etiqueta:** *Grado de acuerdo: Poderosos no le importan personas como uno*  
- **Fraseo:** *A continuación, las siguientes preguntas se refieren a personas que ocupan posiciones de poder, pertenecen a la élite o ejercen algún rol de autoridad, tanto en organizaciones públicas como privadas ¿Qué tan de acuerdo o en desacuerdo está con las siguientes afirmaciones?*

**Variable:** `d24_02`  
**Etiqueta:** *Grado de acuerdo: Poderosos indolentes con problemas graves en mi barrio*  
- **Fraseo:** *A continuación, las siguientes preguntas se refieren a personas que ocupan posiciones de poder, pertenecen a la élite o ejercen algún rol de autoridad, tanto en organizaciones públicas como privadas ¿Qué tan de acuerdo o en desacuerdo está con las siguientes afirmaciones?*

**Variable:** `d24_03`  
**Etiqueta:** *Grado de acuerdo: Poderosos actúan según intereses de grandes empresarios*  
- **Fraseo:** *A continuación, las siguientes preguntas se refieren a personas que ocupan posiciones de poder, pertenecen a la élite o ejercen algún rol de autoridad, tanto en organizaciones públicas como privadas ¿Qué tan de acuerdo o en desacuerdo está con las siguientes afirmaciones?*

**Variable:** `d24_04`  
**Etiqueta:** *Grado de acuerdo: Justicia siempre favorece a poderosos*  
- **Fraseo:** *A continuación, las siguientes preguntas se refieren a personas que ocupan posiciones de poder, pertenecen a la élite o ejercen algún rol de autoridad, tanto en organizaciones públicas como privadas ¿Qué tan de acuerdo o en desacuerdo está con las siguientes afirmaciones?*

# Deprivación relativa

**Variable:** `d27_01`  
**Etiqueta:** *Grado de acuerdo: Insatisfacción al compararme con otros como yo*  
- **Fraseo:** *Por favor, señale su grado de acuerdo o desacuerdo con las siguientes afirmaciones.*

**Variable:** `d27_03`  
**Etiqueta:** *Grado de acuerdo: Insatisfacción al compararme con clases más altas*  
- **Fraseo:** *Por favor, señale su grado de acuerdo o desacuerdo con las siguientes afirmaciones.*

**Variable:** `d27_05`  
**Etiqueta:** *Grado de acuerdo: Personas de mi clase peor que las de clases más altas*  
- **Fraseo:** *Por favor, señale su grado de acuerdo o desacuerdo con las siguientes afirmaciones.*

# Justicia distributiva y meritocracia

**Variable:** `c18_09`  
**Etiqueta:** *Grado de acuerdo: Las personas son recompensadas por sus esfuerzos*  
- **Fraseo:** *¿En qué medida se encuentra usted de acuerdo o en desacuerdo con cada una de las siguientes afirmaciones?*

**Variable:** `c18_10`  
**Etiqueta:** *Grado de acuerdo: Las personas son recompensadas por su inteligencia*  
- **Fraseo:** *¿En qué medida se encuentra usted de acuerdo o en desacuerdo con cada una de las siguientes afirmaciones?*

# Justicia y conflicto social

**Variable:** `d02_02`  
**Etiqueta:** *Grado de acuerdo: Justicia distributiva en educación*  
- **Fraseo:** *Ahora, le leeré una lista de frases. Por favor, señale su grado de acuerdo o desacuerdo con las siguientes afirmaciones, utilizando la siguiente escala de respuesta:*

**Variable:** `d19`  
**Etiqueta:** *Justificación de diferencias entre clases sociales*  
- **Fraseo:** *¿Y cuán justa o injusta cree usted que es la diferencia en la situación de vida entre las personas de clase social alta y las de clase social baja en Chile?*

# Confianza en instituciones

**Variable:** `c05_01`  
**Etiqueta:** *Grado de confianza: El Gobierno*  
- **Fraseo:** *Utilizando una escala donde 1 representa "Nada" y 5 "Mucha", ¿podría decirme cuánto confía usted en cada una de las siguientes instituciones?*

**Variable:** `c05_02`  
**Etiqueta:** *Grado de confianza: Los Partidos Políticos*  
- **Fraseo:** *Utilizando una escala donde 1 representa "Nada" y 5 "Mucha", ¿podría decirme cuánto confía usted en cada una de las siguientes instituciones?*

**Variable:** `c05_07`  
**Etiqueta:** *Grado de confianza: El Congreso Nacional*  
- **Fraseo:** *Utilizando una escala donde 1 representa "Nada" y 5 "Mucha", ¿podría decirme cuánto confía usted en cada una de las siguientes instituciones?*

# Democracia

**Variable:** `c01`  
**Etiqueta:** *Satisfacción con la democracia en Chile*  
- **Fraseo:** *¿Cuán satisfecho o insatisfecho está usted con el funcionamiento de la democracia en Chile?*

